name: autoverpod_library
repository: https://github.com/pckimlong/autoverpod_library
publish_to: none
environment:
  sdk: ^3.9.2

workspace:
  - autoverpod
  - autoverpod_generator


dev_dependencies:
  build_runner: ^2.8.0
