name: autoverpod_generator
description: Code generator for autoverpod annotations to create Riverpod widgets
version: 0.0.7
repository: https://github.com/pckimlong/autoverpod_library
homepage: https://github.com/pckimlong/autoverpod_library
issue_tracker: https://github.com/pckimlong/autoverpod_library/issues

environment:
  sdk: ^3.9.2
resolution: workspace


dependencies:
  source_gen: ^4.0.2
  recase: ^4.1.0
  build: ^4.0.2
  meta: ^1.16.0
  analyzer: ">=7.4.0 <9.0.0"
  riverpod_annotation: ^3.0.3
  dart_style: ^3.1.2
  collection: ^1.19.1
  riverpod: ^3.0.3
  code_builder: ^4.11.0
  path: ^1.9.1
  autoverpod: ^0.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
