name: autoverpod_generator
description: Code generator for autoverpod annotations to create Riverpod widgets
version: 0.0.7
repository: https://github.com/pckimlong/autoverpod_library
homepage: https://github.com/pckimlong/autoverpod_library
issue_tracker: https://github.com/pckimlong/autoverpod_library/issues

environment:
  sdk: 3.9.0-333.2.beta
resolution: workspace


dependencies:
  source_gen: ^4.0.1
  recase: ^4.1.0
  build: ^4.0.0
  meta: ^1.16.0
  analyzer: ^8.1.1 
  riverpod_annotation: ^3.0.0
  dart_style: ^3.0.1
  collection: ^1.19.1
  riverpod: ^3.0.0
  code_builder: ^4.10.1
  path: ^1.9.0
  autoverpod: ^0.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.8.0
